2020-02-05 09:31:31,442 ERROR: Exception on /index [GET] [in /Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/williamkenrick/.pyenv/versions/3.8.0/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/williamkenrick/Projects/python/microblogx/app/main/routes.py", line 29, in index
    raise Exception("============== deliberate ==============")
Exception: ============== deliberate ==============
